---
- name: Check if aws is installed
  ansible.builtin.stat:
    path: /usr/local/bin/aws
  register: aws_install_check

- name: Install AWS cli
  when: configure_aws_cli is true
  block:
    - name: Install unzip package
      become: true
      when: not aws_install_check.stat.exists
      ansible.builtin.apt:
        cache_valid_time: "{{ apt_cache_valid_time }}"
        name:
          - unzip
        state: present

    - name: Download the aws zip
      ansible.builtin.unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp
        remote_src: true
      when: not aws_install_check.stat.exists

    - name: Install the aws binary
      ansible.builtin.command: /tmp/aws/install
      args:
        creates: /usr/local/bin/aws
      when: not aws_install_check.stat.exists

    - name: Clean up the build directory
      ansible.builtin.file:
        path: /tmp/aws
        state: absent
